# Generated by Django 2.1.5 on 2019-02-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='costomer',
            new_name='customer',
        ),
    ]
